services:
  postgres:
    image: postgres:16
    container_name: postgres
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: app
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./docker/init:/docker-entrypoint-initdb.d      
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U app"]
      interval: 5s
      timeout: 5s
      retries: 5

  plagiarism_service:
    build:
      context: ./
    container_name: plagiarism_service
    env_file:
      - ./.env
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "8003:8000"

volumes:
  postgres_data: