"""init

Revision ID: b6215a55c570
Revises: 
Create Date: 2026-05-24 22:17:01.989415

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b6215a55c570'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('code_submissions',
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('language', sa.String(length=50), nullable=False),
    sa.Column('task_id', sa.Integer(), nullable=False),
    sa.Column('code_hash', sa.String(length=64), nullable=False),
    sa.Column('code', sa.Text(), nullable=False),
    sa.Column('submissionDate', sa.TIMESTAMP(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_task_hash', 'code_submissions', ['task_id', 'code_hash'], unique=False)
    op.create_index(op.f('ix_code_submissions_code_hash'), 'code_submissions', ['code_hash'], unique=False)
    op.create_index(op.f('ix_code_submissions_task_id'), 'code_submissions', ['task_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_code_submissions_task_id'), table_name='code_submissions')
    op.drop_index(op.f('ix_code_submissions_code_hash'), table_name='code_submissions')
    op.drop_index('idx_task_hash', table_name='code_submissions')
    op.drop_table('code_submissions')
    # ### end Alembic commands ###
